### ISSUE TITLE
Updated masternode not starting 

### ISSUE THREAD

**Issue by javonjw** [HugoPhoenix/Polar#5]
This issue tracker is only for technical issues related to Polar Core.
General Polar questions and/or support requests and are best directed to the [Polar Discord](https://discord.polar.org).

### Describe the issue
Cant start masternode with new collateral peers are getting banned my masternode is up with new wallet ip is [2a02:c207:2033:9221:c21b::5]:31046 it comes up in peers 

#### If so, please list the steps to reproduce below:
1. Sent 25000 to self 
2.Transaction ID: 7aee225254453a1a26ea87d313f6d79154a5432113a7313eae2b71b8cc57dc4e
3.Status: 93 confirmations

### Expected behavior
Tell us what should happen
should be able to start missing masternode

### Actual behavior
Tell us what happens instead
startmasternode "alias" "0" "9467a620-1f97-44aa-8433-eca234fc0cf9"

20:21:23
￼
{
  "overall": "Successfully started 0 masternodes, failed to start 1, total 1",
  "detail": [
    {
      "alias": "9467a620-1f97-44aa-8433-eca234fc0cf9",
      "result": "failed",
      "errorMessage": "Could not allocate vin 7aee225254453a1a26ea87d313f6d79154a5432113a7313eae2b71b8cc57dc4e:1 for masternode [2a02:c207:2033:9221:c21b::5]:31046"

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Polar Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by HugoPhoenix** [comment]
Masternodes' Collateral increase to 25000 PA

**Comment by HugoPhoenix** [comment]
there is an error found, causing masternode unable to set up. v1.1.0.1 will be available in a day, sorry about this
